apiVersion: v1
kind: Service
metadata:
  name: hello-app
  labels: 
    app: hello-app
spec:
  selector:
    app: hello-app
  type: LoadBalancer
  ports: 
  - name: hello-app-service
    port: 1234
    targetPort: 8080
    protocol: TCP