apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: "hello-app"
  labels:
    app: "hello-app"

spec:
  selector:
    matchLabels:
      app: "hello-app"
  replicas: 2
  template:
    metadata:
      labels:
        app: "hello-app"
    spec:
      containers:
        - name: "hello-app"
          image: "gabrielminoru/hello-app"

